### ISSUE TITLE
Request for override

### ISSUE THREAD

**Issue by BulbsOnBenito** [whitesoup12/remote-falcon-tracker#90] opened 2021-02-14 19:03 UTC
I would like to request an override option for the owner logged in on a device into remote falcon to be able to enter a customizable pin and be able to have the song they choose next play.

**Comment by whitesoup12** [comment] 2021-04-23 13:18
Duplicate of #20

**Comment by BulbsOnBenito** [comment] 2021-04-23 14:21
wait you did it?!? YAY

Darren Johnson

**Comment by whitesoup12** [comment] 2021-04-23 14:27
lol, no. Was just noting that this request is a duplicate of (or similar to) another request. Still need to work on this one.

**Comment by BulbsOnBenito** [comment] 2021-04-23 14:40
ok lol thank you! i’m excited still

Darren Johnson

**Closed** 2021-04-28 16:58 UTC
Labels: done, duplicate, enhancement

**Comment by BulbsOnBenito** [comment] 2021-04-28 17:06
what does closed me sorry lol

Darren Johnson

**Comment by whitesoup12** [comment] 2021-04-28 17:17
It's been done. :)

**Comment by BulbsOnBenito** [comment] 2021-04-28 17:18
YAY! how does it work?! omgosh yay

Darren Johnson

**Comment by whitesoup12** [comment] 2021-04-28 17:41
https://github.com/whitesoup12/remote-falcon-tracker/wiki/Remote-Falcon-Wiki#play-sequence
