### ISSUE TITLE
CNAME support

### ISSUE THREAD

**Issue by JRTRED** [whitesoup12/remote-falcon-tracker#113] opened 2021-08-31 20:20 UTC
Currently I do a redirect from a custom domain. Would love to see CNME support so the domain is pointed rather that redirected.

**Comment by JRTRED** [comment] 2021-08-31 20:57
oh shit, I see this was already requested.

**Comment by Jchuchla** [comment] 2021-12-04 01:21
Add one more vote for this!

**Comment by whitesoup12** [comment] 2021-12-21 14:09
Duplicate of #53

**Closed by whitesoup12** 2021-12-21 14:09 UTC
Labels: duplicate
